name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
  id-token: write # Required for OpenID Connect (OIDC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: oven-sh/setup-bun@v2.2.0

      - run: bun install --frozen-lockfile

      - name: Build & verify
        run: bun run build

      - name: Pack
        run: npm pack --pack-destination .

      - name: Publish to npm
        run: npm publish --provenance

      - name: Generate checksum
        run: sha256sum pi-plugin-manager-*.tgz > checksums.txt

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            pi-plugin-manager-*.tgz
            checksums.txt
          generate_release_notes: true
